spring:
  application.name: CredFlow
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  mvc:
    locale: pt_BR
    locale-resolver: fixed
  messages:
    basename: ValidationMessages
    encoding: UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /credflow/api
  port: ${PORT:8080}
  forward-headers-strategy: native
  compression.enabled: true
  shutdown: graceful

management:
  server.base-path: /actuator
  endpoints.web.exposure.include: health,info
  endpoint.health.probes.enabled: true

jwt:
  secret: ${JWT_SECRET:local-test-secret}
  expiration: ${JWT_EXPIRATION_MS:3600000}

app:
  mail:
    from: noreply@credflow.com
  frontend:
    url: http://localhost:3000

spring.mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:}
  password: ${MAIL_PASSWORD:}
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha
