spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/credflow
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: false

server:
  port: 8080